# Generated by Django 4.2.10 on 2026-01-27 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('batches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student'),
        ),
    ]
