# Generated by Django 4.2.10 on 2026-01-27 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='coach_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches_coached', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='batchenrollment',
            unique_together={('student', 'batch')},
        ),
    ]
