# Generated by Django 5.2.10 on 2026-01-27 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0004_coachavailability_reschedulerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reschedulerequest',
            name='original_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_source', to='batches.batch'),
        ),
    ]
