# Generated by Django 5.2.10 on 2026-01-28 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0005_alter_reschedulerequest_original_batch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='max_students',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.CreateModel(
            name='CoachBatchApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('application_message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('admin_notes', models.TextField(blank=True)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_applications', to='batches.batch')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('batch', 'coach')},
            },
        ),
    ]
