# Generated by Django 5.2.10 on 2026-01-28 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0007_alter_batch_coach_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchenrollment',
            name='enrollment_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
