# Generated by Django 5.2.10 on 2026-02-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0008_alter_batchenrollment_enrollment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='batch_type',
            field=models.CharField(choices=[('RECURRING', 'Recurring'), ('ONE_TIME', 'One-time')], default='RECURRING', max_length=15),
        ),
        migrations.AddField(
            model_name='batch',
            name='exact_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('FINISHED', 'Finished')], default='ACTIVE', max_length=10),
        ),
    ]
