# Generated by Django 4.2.10 on 2026-01-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='verification sent at'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=100, verbose_name='email verification token'),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_password_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='password reset sent at'),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_password_token',
            field=models.CharField(blank=True, max_length=100, verbose_name='password reset token'),
        ),
    ]
