# Generated by Django 5.2.10 on 2026-01-28 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournamentregistration_attended_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentregistration',
            name='attended',
        ),
        migrations.AddField(
            model_name='tournamentregistration',
            name='attendance_status',
            field=models.CharField(blank=True, choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tournamentregistration',
            name='fee_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='tournamentregistration',
            name='registered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_tournaments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournamentregistration',
            name='registration_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
