# Generated by Django 5.2.10 on 2026-02-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_remove_tournamentregistration_attended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentregistration',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
