# Generated by Django 4.2.10 on 2026-04-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='nic',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
